// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsO09tGnqs4Ii62FWa_t6geenukTTN7qw',
    appId: '1:820638733399:web:7cdc6e5ad9d435a82fff12',
    messagingSenderId: '820638733399',
    projectId: 'moneywave-84d65',
    authDomain: 'moneywave-84d65.firebaseapp.com',
    storageBucket: 'moneywave-84d65.appspot.com',
    measurementId: 'G-FZ6HS7PM84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEAQW2NI6B7tujVQu51DHNSOpuBP8bdeE',
    appId: '1:820638733399:android:af2af412316271692fff12',
    messagingSenderId: '820638733399',
    projectId: 'moneywave-84d65',
    storageBucket: 'moneywave-84d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApIswgccnqzmMAxRMgkkvXp3fx1kLqyJ4',
    appId: '1:820638733399:ios:d68b397587cfdb442fff12',
    messagingSenderId: '820638733399',
    projectId: 'moneywave-84d65',
    storageBucket: 'moneywave-84d65.appspot.com',
    androidClientId: '820638733399-k05udbnud95sjiuu4jubkfoofu1dudgl.apps.googleusercontent.com',
    iosClientId: '820638733399-7o2kjks8kos3bi3lh1qcpfi6cpg2k2hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mwave',
  );
}
